### ISSUE TITLE
Write the Basics / Background chapter

### ISSUE THREAD

**Issue by joachimrussig** [joachimrussig/GI_Forum_2017_Paper#4]
# Structure / Content

The Basics / Background chapter should cover some of the most important basics:

- Thermal Comfort:
  - meteorological parameters influencing the thermal perception: air temperature, humidity, wind and solar radiation
  - measures for thermal comfort: heat index, UTCI, perceived temperature
- Routing
  - static and dynamic route planning problems
  - modelling: time-dependent
  - complexity

# Alternatives
Merge with the introduction (issue #2)?

**Comment by joachimrussig** [comment]
I wonder: should routing be part of the basic chapter or isn't it better to include the routing basics in the main part?

**Comment by JulianBruns** [comment]
The main points of routing should be in the related work from my point of view. -> What exist till now, and then later your/our approach in the main part

**Comment by joachimrussig** [comment]
Me current consideration is to rename the basics section to 'Thermal Comfort' and cover conly thermal comfort basics. The routing basics (modelling as graph, stativ vs. dynamic routing, NP-hardness, etc.) can be coverd briefly in the main part as well.

**Comment by JulianBruns** [comment]
That is ok as well. But Thermal Comfort could be reduced to related work / very small sub-chapter in introduction/subsection. 
This can be assumed as given from literature

**Comment by joachimrussig** [comment]
You're right. I'm merging thermal comfort as a small subsection into the introduction (#2).
