### ISSUE TITLE
Create Structure

### ISSUE THREAD

**Issue by JulianBruns** [joachimrussig/GI_Forum_2017_Paper#6]
Based on Story, what kind of structure is our goal?

**Comment by joachimrussig** [comment]
In [STRUCTURE.md](https://github.com/joachimrussig/GI_Forum_2017_Paper/blob/master/STRUCTURE.md) I wrote a first rough structure of the paper, but I'm happy about your feedback.

I've started to open an issue for each chapter where we can discuss the details. If we'd like to change the structure we can close those issues in favor of new ones.
