### ISSUE TITLE
Ensure that the paper is compliant with the author guidelines

### ISSUE THREAD

**Issue by joachimrussig** [joachimrussig/GI_Forum_2017_Paper#8]
Unfortunately there is no LaTeX template, so we have to ensure that our manuscript is complaint with the [author guidelines](http://www.gi-forum.org/images/Forms/Documents2017/2017Journal_Instructions_for_Authors_FINAL.pdf):

- [x] Manuscript preparation:
  - [x] max. 5000 words including tables, references, captions, footnotes and endnotes  
  - [x] Abstracts of 150 - 200 words
  - [x] 3 to 5 keywords
  - [x] Manuscripts prepared for the double-blind review must be anonymised
  - [x] Use  APA style  for  in-text  references  and  reference  list (http://www.apastyle.org/). 
  - [x] Therefore, manuscripts should contain the following: 
     - **For review:** title; abstract; keywords; main text; reference list; appendices (as 
appropriate); table(s) and figure(s) placed in the correct location in the text
including capturing, cross-referencing and numbering
    - **For publication (final version):** title; author(s) and affiliation(s); abstract; keywords; main  text;  acknowledgment(s);  reference  list;  appendices;  table(s)  and  figure(s) placed  in  the  correct  location  in  the  textusing  manual  numbering  and  cross-referencing 
  - [x] British English spelling and punctuation are preferred. Please use double quotation marks (“”).
  - [x] International System (SI) units
- [x] Layout Style Guidelines:
  - [x] Manuscripts shall be submitted as running text without any further formatting 
  - [x] Abstract: Indicate the abstract paragraph with a heading
  - [x] Headings to a maximum of three levels have to be included as follows: 1, 1.1, 1.1.1
  - [x] Tables and figures: Place the tables and figures in the text where these should appear. Ensure you have permission to use any figures you are reproducing from another source; automatic capturing,  cross-referencing  and  numbering  only  to  be  used  in  the  review  version  of  the manuscript
  - [x] Provide the highest quality figure format possible. Please be sure that all imported scanned material is scanned at an appropriate resolution: 1200 dpi for line art, 600 dpi for grayscale and 300 dpi for colour. All graphics should be submitted at a resolution of at least 600 dpi.
  - ~~[ ] For the final version provide all graphics in a separate file in a jpg, png or tiff format~~ (final version only)
  - [x] Maximum width for figures is 17 cm
  - [x] Anonymity: ensure your identity and that of your co-authors is not revealed in the text of your article or in your manuscript files when submitting the manuscript for review
  - [x] Author names, affiliation(s), and acknowledgements are only to be included in the final version
- [x] Anonymization of your manuscript for double-blind peer review

**Comment by joachimrussig** [comment]
Respective the APA style: is it sufficient to use the APA biblatex style or do we need to double check with the official APA guidelines?

**Comment by JulianBruns** [comment]
APA bibtex should be sufficient
