### ISSUE TITLE
Write the main part (Routing / Optimal Time)

### ISSUE THREAD

**Issue by joachimrussig** [joachimrussig/GI_Forum_2017_Paper#9]
# Structure / Content

The main part should cover the key ideas of our approach, as well how we obtained our goals:

- [x] Routing
  - [x] modelling the routing network
  - [x] complexity
  - [x] edge weighting
  - [x] mapping raster to the road network (later?)
- [x] Finding the optimal point in time
  - [x] modelling as optimzation problem / constrains
  - [x] objective function
  - [x] optimization

**Comment by JulianBruns** [comment]
seems good.
